services:

  postgres:
    image: postgres:18
    container_name: gerador-times-postgres
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${PG_DATABASE}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: gerador-times-api
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
volumes:
  postgres_data: