services:
  postgres:
    image: postgres:18
    container_name: gerador-times-postgres
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${PG_DATABASE}" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: