spring.config.import=optional:file:.env[.properties]

spring.application.name=${APP_NAME}

server.error.include-stacktrace=never
spring.mvc.problemdetails.enabled=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.profiles.default=${SPRING_PROFILES_ACTIVE:dev}