spring.application.name=geradortimes

# SERVER CONFIGURATION
server.error.include-stacktrace=never
spring.mvc.problemdetails.enabled=true

# DATA SOURCE
spring.datasource.url=${JDBC_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# AUTH (JWT)
auth.jwt.secret=${JWT_SECRET}
auth.jwt.issuer=${JWT_ISSUER:geradortimes}
auth.jwt.access-token-ttl=${JWT_ACCESS_TTL:15m}
auth.jwt.refresh-token-ttl=${JWT_REFRESH_TTL:30d}
auth.jwt.refresh-token-salt=${JWT_REFRESH_SALT}

# AUTH COOKIE (refresh token)
auth.cookie.refresh-token-name=${AUTH_COOKIE_REFRESH_NAME}
auth.cookie.path=${AUTH_COOKIE_PATH}
auth.cookie.secure=${AUTH_COOKIE_SECURE}
auth.cookie.same-site=${AUTH_COOKIE_SAMESITE}

argon.hash.pepper = ${ARGON_PEPPER}

# OPENAPI / SWAGGER
springdoc.swagger-ui.persistAuthorization=true
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.tagsSorter=alpha
